@echo off
rem Easier to launch client...
rem -Sheriff

echo Launching localhost client...
echo Game is in portguese...
echo ===============================
ppython main.py -svaddr localhost -l pt
echo ===============================
echo Client ended...
pause