@echo off
rem Easier to launch client...
rem -Sheriff

echo Launching localhost client...
echo Game is in french...
echo ===============================
ppython main.py -svaddr localhost -l fr
echo ===============================
echo Client ended...
pause