@echo off
rem Easier to launch client...
rem -Sheriff

echo Launching localhost client...
echo Game is in japanese...
echo ===============================
ppython main.py -svaddr localhost -l jp
echo ===============================
echo Client ended...
pause